name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para que semantic-release pueda leer todos los tags

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # O la versión que uses

      - name: Install dependencies
        run: |
          pip install python-semantic-release==9.21.0 build twine setuptools
          pip install -r requirements.txt

      - name: Configure Git (necesario si semantic-release hace commits)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release version
          git push origin master --follow-tags
